// 100 original answers for the Book of Answer
const answers = [
  "Yes — without a doubt.",
  "No — not this time.",
  "The stars align in your favor.",
  "Patience will reveal the truth.",
  "Look within for the answer.",
  "The path forward is unclear, but take it anyway.",
  "Something unexpected will change everything.",
  "Trust your instincts.",
  "The answer already lives in your heart.",
  "Not yet — the timing isn't right.",
  "A surprise awaits you.",
  "Let go of what you cannot control.",
  "The universe says yes.",
  "Seek counsel from someone you trust.",
  "A new door is about to open.",
  "Focus on what truly matters.",
  "The risk is worth the reward.",
  "Change is coming — embrace it.",
  "You already know the answer.",
  "Wait three days, then act.",
  "An opportunity disguised as a problem.",
  "Say yes to the unknown.",
  "The answer is closer than you think.",
  "No — but something better awaits.",
  "Follow the energy, not the logic.",
  "A secret will be revealed.",
  "You are on the right path.",
  "Let this one go.",
  "Courage will carry you through.",
  "The answer is in the silence.",
  "A journey begins with a single step.",
  "What you seek is seeking you.",
  "Release your expectations.",
  "The universe has other plans.",
  "Trust the process.",
  "A message from the beyond: yes.",
  "The winds of change blow in your favor.",
  "Not now, but soon.",
  "Look for the sign — it's already there.",
  "Your intuition is correct.",
  "The answer is no, but it's a blessing.",
  "Something beautiful is about to unfold.",
  "Stay grounded and the answer will come.",
  "A leap of faith is required.",
  "The truth will set you free.",
  "Align your actions with your purpose.",
  "An unexpected ally will appear.",
  "The answer lies in the question itself.",
  "Yes, but be prepared for detours.",
  "Surrender and find your power.",
  "A chapter is ending — turn the page.",
  "The light is green. Go.",
  "Not everything is as it seems.",
  "Your wish will come true, differently than expected.",
  "Hold steady. The storm will pass.",
  "A forgotten memory holds the key.",
  "The answer is yes, wholeheartedly.",
  "Rejection is redirection.",
  "Meditate on it, then decide.",
  "Fortune favors the bold.",
  "The cosmos conspires for you.",
  "A small yes leads to a big yes.",
  "Listen more, speak less.",
  "The answer is unfolding as you read this.",
  "Forgive, then move forward.",
  "Your patience will be rewarded.",
  "Something you lost will return.",
  "The answer is hidden in plain sight.",
  "Take the road less traveled.",
  "A powerful transformation is near.",
  "The answer is yes — with conditions.",
  "You are exactly where you need to be.",
  "A dream holds the answer.",
  "Let your heart decide.",
  "The universe is listening.",
  "No more waiting — act now.",
  "An old wound will finally heal.",
  "The answer is a gentle no.",
  "Your creativity will light the way.",
  "A sign from above: trust.",
  "The pieces are falling into place.",
  "Say it out loud and see how it feels.",
  "A door closes, a window opens.",
  "The answer is yes — absolutely.",
  "Your higher self already knows.",
  "A beautiful coincidence is coming.",
  "The answer is maybe — and that's okay.",
  "Trust the timing of your life.",
  "A powerful yes echoes through the void.",
  "Let the answer surprise you.",
  "The oracle speaks: proceed.",
  "Your energy is magnetic right now.",
  "The answer is written in the stars.",
  "A breakthrough is imminent.",
  "Let love guide your decision.",
  "The answer is yes — but differently than you imagined.",
  "You are protected. Move forward.",
  "A revelation changes everything.",
  "The answer is no — and you'll thank yourself later.",
  "The universe whispers: not yet.",
  "Your destiny awaits.",
  "A cosmic wink: everything will be alright.",
];

export default answers;
